# Generated by Django 5.0.6 on 2024-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(null=True, upload_to='songs/'),
        ),
    ]
